# Generated by Django 2.2.28 on 2023-03-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='owner',
        ),
    ]
